### ISSUE TITLE
 'module' object has no attribute 'packages' when installing counterparty-cli

### ISSUE THREAD

**Issue by cryptodock** [CounterpartyXCP/counterpartyd#711]
Hi,
I am trying to install counterparty cli with 2 methods and both fail on ubuntu 14.04 64bit

method1: sudo pip3 install counterparty-cli --pre
method2: 
git clone https://github.com/CounterpartyXCP/counterparty-cli.git
cd counterparty-cli
python3 setup.py install

both results in same error: AttributeError: 'module' object has no attribute 'packages'

**Comment by rippler** [comment]
`--pre` was for prerelease, so at the moment it doesn't do anything (as there are no prereleases). 
See https://github.com/CounterpartyXCP/counterparty-cli/issues/23 for more on this issue.
You can try to upgrade the requests package to a version specified in this link (`sudo pip3 install --upgrade requests==version`) and then try again.

**Comment by ouziel-slama** [comment]
fixed here: https://github.com/CounterpartyXCP/counterparty-cli/commit/f1d9a974ec0a1979509e0608c87c4bca34c7f746

**Comment by cryptodock** [comment]
still not working:

 sudo pip3 install --upgrade requests==2.5.1
Requirement already up-to-date: requests==2.5.1 in /usr/local/lib/python3.4/dist-packages
Cleaning up...

counterparty-server
Traceback (most recent call last):
  File "/usr/local/bin/counterparty-server", line 9, in <module>
    load_entry_point('counterparty-cli==1.0.0', 'console_scripts', 'counterparty-server')()
  File "/usr/local/lib/python3.4/dist-packages/counterparty_cli-1.0.0-py3.4.egg/counterpartycli/__init__.py", line 15, in server_main
    from counterpartycli import server
  File "/usr/local/lib/python3.4/dist-packages/counterparty_cli-1.0.0-py3.4.egg/counterpartycli/server.py", line 10, in <module>
    log.set_up(logger)
  File "/usr/local/lib/python3.4/dist-packages/counterparty_lib-9.49.4-py3.4.egg/counterpartylib/lib/log.py", line 55, in set_up
    requests.packages.urllib3.disable_warnings()
AttributeError: 'module' object has no attribute 'packages'


sudo pip3 uninstall counterparty-cli
Uninstalling counterparty-cli:
  /usr/local/lib/python3.4/dist-packages/counterparty_cli-1.0.0-py3.4.egg
Proceed (y/n)? y
  Successfully uninstalled counterparty-cli


install fails:

AttributeError: 'module' object has no attribute 'packages'

----------------------------------------
Cleaning up...
Command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/counterparty-cli/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-1oks0pio-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/counterparty-cli
Storing debug log for failure in /home/counterparty/.pip/pip.log

**Comment by rippler** [comment]
Can you post the end of `/home/counterparty/.pip/pip.log`?

**Comment by ouziel-slama** [comment]
Are you sure, you are using the same env. when you run `pip install` and `counterparty-server` ?
If you really have the version 2.5.1 installed there is no reason to get this error message.

**Comment by cryptodock** [comment]
AttributeError: 'module' object has no attribute 'packages'
ouziel-slama  I use same env, I understand what you are saying but it still doesn't work.

rippler end of /home/counterparty/.pip/pip.log
----------------------------------------
Cleaning up...
  Removing temporary dir /tmp/pip_build_root...
Command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/counterparty-cli/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record $
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1435, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 706, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/usr/lib/python3/dist-packages/pip/util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/counterparty-cli/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __f$

**Comment by adamkrellenstein** [comment]
Let's verify that this isn't an issue with the codebase.

**Comment by adamkrellenstein** [comment]
@cryptodock, have tried this?
```
git clone https://github.com/CounterpartyXCP/counterparty-cli.git --branch develop
cd counterparty-cli
sudo pip3 install --upgrade -r requirements.txt
sudo python3 setup.py install 
```

**Comment by rippler** [comment]
Gee, problem is freaking annoying! Sometimes a workaround (either installing from develop or deleting the requests package) works, sometimes not. 

Here's what always works for me: **before** Adam's recipe above, do this:
```
wget https://raw.github.com/pypa/pip/master/contrib/get-pip.py
sudo python3 get-pip.py
sudo pip3 install requests==2.5.1
```
(I think the last line from Adam's recipe, `sudo python3 setup.py install`, may not ever be necessary, but you can run it anyway).

Feel free to first test on a non-production system.
I don't know how to reliably work around the issue in any other way.

**Comment by cryptodock** [comment]
rippler
First I went ahead and uninstalled requests ( made sure nothing left in the dir as well)
>   sudo pip3 uninstall requests
>   Successfully uninstalled requests-2.5.1

Then I did 
> wget https://raw.github.com/pypa/pip/master/contrib/get-pip.py
> sudo python3 get-pip.py
> sudo pip3 install requests==2.5.1

Results:

> Collecting requests==2.5.1
>  Downloading requests-2.5.1-py2.py3-none-any.whl (464kB)
>   100% |################################| 466kB 1.7MB/s
> Installing collected packages: requests

>Successfully installed requests-2.5.1

Now Adams's recipe:

> Obtaining file:///home/counterparty/counterparty-cli (from -r requirements.txt (line 4))
>    Installed /home/counterparty/counterparty-cli/counterparty_lib-9.49.4-py3.4.egg
> Requirement already up-to-date: requests>=2.5.1 in /usr/local/lib/python3.4/dist-packages (from -r  requirements.txt (line 3))
> Requirement already up-to-date: appdirs in /usr/local/lib/python3.4/dist-packages (from counterparty-cli==1.0.0->-r requirements.txt (line 4))
Requirement already up-to-date: prettytable in /usr/local/lib/python3.4/dist-packages (from counterparty-cli==1.0.0->-r requirements.txt (line 4))
Requirement already up-to-date: colorlog in /usr/local/lib/python3.4/dist-packages (from counterparty-cli==1.0.0->-r requirements.txt (line 4))
Requirement already up-to-date: python-dateutil in /usr/local/lib/python3.4/dist-packages (from counterparty-cli==1.0.0->-r requirements.txt (line 4))
Requirement already up-to-date: counterparty-lib in ./counterparty_lib-9.49.4-py3.4.egg (from counterparty-cli==1.0.0->-r requirements.txt (line 4))
Requirement already up-to-date: six>=1.5 in /usr/local/lib/python3.4/dist-packages (from python-dateutil->counterparty-cli==1.0.0->-r requirements.txt (line 4))
Requirement already up-to-date: flask>=0.10.1 in /usr/local/lib/python3.4/dist-packages (from counterparty-lib->counterparty-cli==1.0.0->-r requirements.txt (line 4))
Requirement already up-to-date: Flask-HTTPAuth>=2.3.0 in /usr/local/lib/python3.4/dist-packages (from counterparty-lib->counterparty-cli==1.0.0->-r requirements.txt (line 4))
Requirement already up-to-date: json-rpc>=1.7 in /usr/local/lib/python3.4/dist-packages (from counterparty-lib->counterparty-cli==1.0.0->-r requirements.txt (line 4))
Requirement already up-to-date: pytest>=2.6.4 in /usr/local/lib/python3.4/dist-packages (from counterparty-lib->counterparty-cli==1.0.0->-r requirements.txt (line 4))
Requirement already up-to-date: pytest-cov>=1.8.0 in /usr/local/lib/python3.4/dist-packages (from counterparty-lib->counterparty-cli==1.0.0->-r requirements.txt (line 4))
Requirement already up-to-date: pycoin>=0.52 in /usr/local/lib/python3.4/dist-packages (from counterparty-lib->counterparty-cli==1.0.0->-r requirements.txt (line 4))
Requirement already up-to-date: tornado>=4.0 in /usr/local/lib/python3.4/dist-packages (from counterparty-lib->counterparty-cli==1.0.0->-r requirements.txt (line 4))
Requirement already up-to-date: pycrypto>=2.6 in /usr/local/lib/python3.4/dist-packages (from counterparty-lib->counterparty-cli==1.0.0->-r requirements.txt (line 4))
Requirement already up-to-date: tendo>=0.2.6 in /usr/local/lib/python3.4/dist-packages (from counterparty-lib->counterparty-cli==1.0.0->-r requirements.txt (line 4))
Requirement already up-to-date: pysha3>=0.3 in /usr/local/lib/python3.4/dist-packages (from counterparty-lib->counterparty-cli==1.0.0->-r requirements.txt (line 4))
Requirement already up-to-date: python-bitcoinlib>=0.2.1 in /usr/local/lib/python3.4/dist-packages (from counterparty-lib->counterparty-cli==1.0.0->-r requirements.txt (line 4))
Requirement already up-to-date: Werkzeug>=0.7 in /usr/local/lib/python3.4/dist-packages (from flask>=0.10.1->counterparty-lib->counterparty-cli==1.0.0->-r requirements.txt (line 4))
Requirement already up-to-date: Jinja2>=2.4 in /usr/local/lib/python3.4/dist-packages (from flask>=0.10.1->counterparty-lib->counterparty-cli==1.0.0->-r requirements.txt (line 4))
Requirement already up-to-date: itsdangerous>=0.21 in /usr/local/lib/python3.4/dist-packages (from flask>=0.10.1->counterparty-lib->counterparty-cli==1.0.0->-r requirements.txt (line 4))
Requirement already up-to-date: py>=1.4.25 in /usr/local/lib/python3.4/dist-packages (from pytest>=2.6.4->counterparty-lib->counterparty-cli==1.0.0->-r requirements.txt (line 4))
Requirement already up-to-date: coverage<4.0a1,>=3.7.1 in /usr/local/lib/python3.4/dist-packages (from pytest-cov>=1.8.0->counterparty-lib->counterparty-cli==1.0.0->-r requirements.txt (line 4))
Requirement already up-to-date: cov-core>=1.14.0 in /usr/local/lib/python3.4/dist-packages (from pytest-cov>=1.8.0->counterparty-lib->counterparty-cli==1.0.0->-r requirements.txt (line 4))
Requirement already up-to-date: certifi in /usr/local/lib/python3.4/dist-packages (from tornado>=4.0->counterparty-lib->counterparty-cli==1.0.0->-r requirements.txt (line 4))
Requirement already up-to-date: markupsafe in /usr/local/lib/python3.4/dist-packages (from Jinja2>=2.4->flask>=0.10.1->counterparty-lib->counterparty-cli==1.0.0->-r requirements.txt (line 4))
> Installing collected packages: counterparty-cli
>  Running setup.py develop for counterparty-cli
>  Checking .pth file support in /usr/local/lib/python3.4/dist-packages/
>  /usr/bin/python3 -E -c pass
>  TEST PASSED: /usr/local/lib/python3.4/dist-packages/ appears to support .pth files
>  Creating /usr/local/lib/python3.4/dist-packages/counterparty-cli.egg-link (link to .)
>  counterparty-cli 1.0.0 is already the active version in easy-install.pth
> Installing counterparty-server script to /usr/local/bin
> Installing counterparty-client script to /usr/local/bin
>  Installed /home/counterparty/counterparty-cli
> Successfully installed counterparty-cli-1.0.0

Yet final result is the same:

counterparty@ns511291:~/counterparty-cli$ sudo counterparty-server
Traceback (most recent call last):
  File "/usr/local/bin/counterparty-server", line 9, in <module>
    load_entry_point('counterparty-cli==1.0.0', 'console_scripts', 'counterparty-server')()
  File "/home/counterparty/counterparty-cli/counterpartycli/__init__.py", line 15, in server_main
    from counterpartycli import server
  File "/home/counterparty/counterparty-cli/counterpartycli/server.py", line 10, in <module>
    log.set_up(logger)
  File "/home/counterparty/counterparty-cli/counterparty_lib-9.49.4-py3.4.egg/counterpartylib/lib/log.py", line 55, in set_up
    requests.packages.urllib3.disable_warnings()
AttributeError: 'module' object has no attribute 'packages'

**Comment by cryptodock** [comment]
Wee I finally managed to fix this issue.

It looks like Ubuntu/Python completely ignores the packages installed via pip3 if it have the same package installed by APT beforehand. Once I removed python3-requests via APT and followed @rippler  method I managed to get counterparty-server up and running.

I really appreciate the help from everone on here ( @rippler , @ouziel-slama , @adamkrellenstein ) - Thank you!
